#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill for Windows PowerShell.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

$ErrorActionPreference = "Stop"

$TOTAL_STAGES = 0
$script:_STAGE_INDEX = 0
$script:ENV_FILE = if ($env:ENV_FILE) { $env:ENV_FILE } else { ".env" }
$script:WRITTEN_ENV = [System.Collections.Generic.List[string]]::new()
$script:WRITTEN_SECRET = [System.Collections.Generic.List[string]]::new()
$script:SKIPPED = [System.Collections.Generic.List[string]]::new()

function Clear-ScreenSafe {
    try { [Console]::Clear() } catch { Write-Host "`n`n`n" }
}

function banner([string]$title) {
    Clear-ScreenSafe
    Write-Host "`n  $title" -ForegroundColor Cyan
    Write-Host "  $TOTAL_STAGES stages`n" -ForegroundColor DarkGray
    Write-Host "  You drive the browser; this wizard tells you exactly what to do and" -ForegroundColor DarkGray
    Write-Host "  captures the values you copy back. Stop any time with Ctrl+C and re-run" -ForegroundColor DarkGray
    Write-Host "  later, since it remembers values already saved.`n" -ForegroundColor DarkGray
    pause "Ready to start?"
}

function stage([string]$name) {
    Clear-ScreenSafe
    $script:_STAGE_INDEX++
    Write-Host "`n▸ Stage $_STAGE_INDEX/$TOTAL_STAGES · $name" -ForegroundColor Cyan
}

function say([string]$msg) {
    Write-Host "  $msg"
}

function step([string]$msg) {
    Write-Host "  • " -ForegroundColor Cyan -NoNewline
    Write-Host $msg
}

function note([string]$msg) {
    Write-Host "  $msg" -ForegroundColor DarkGray
}

function warn([string]$msg) {
    Write-Host "  ⚠ $msg" -ForegroundColor Yellow
}

function open_url([string]$url) {
    Write-Host "  ↗ opening " -ForegroundColor Green -NoNewline
    Write-Host $url
    try {
        Start-Process $url
    } catch {
        warn "Could not open browser automatically; visit manually: $url"
    }
}

function pause([string]$msg = "Press Enter to continue") {
    Write-Host "  $msg " -ForegroundColor DarkGray -NoNewline
    [void][System.Console]::ReadLine()
}

function confirm([string]$question) {
    Write-Host "  ? $question [y/N] " -ForegroundColor Yellow -NoNewline
    $ans = [System.Console]::ReadLine()
    return ($ans -match '^(y|yes)$')
}

function Get-ExistingEnv([string]$key) {
    if (-not (Test-Path $script:ENV_FILE)) { return $null }
    $lines = Get-Content $script:ENV_FILE -ErrorAction SilentlyContinue
    foreach ($line in $lines) {
        if ($line -match "^\s*$([regex]::Escape($key))\s*=\s*(.*)$") {
            return $matches[1].Trim()
        }
    }
    return $null
}

function ask([string]$key, [string]$prompt) {
    $current = Get-ExistingEnv $key
    if ($current) {
        Write-Host "  $prompt " -NoNewline
        Write-Host "[Enter keeps current] " -ForegroundColor DarkGray -NoNewline
    } else {
        Write-Host "  $prompt " -NoNewline
    }
    $inputVal = [System.Console]::ReadLine()
    if ([string]::IsNullOrWhiteSpace($inputVal) -and $current) {
        $inputVal = $current
    }
    Set-Variable -Name $key -Value $inputVal -Scope 1
    return $inputVal
}

function ask_secret([string]$key, [string]$prompt) {
    $current = Get-ExistingEnv $key
    if ($current) {
        Write-Host "  $prompt " -NoNewline
        Write-Host "[Enter keeps current] " -ForegroundColor DarkGray -NoNewline
    } else {
        Write-Host "  $prompt " -NoNewline
    }
    $sec = Read-Host -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
    $inputVal = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    if ([string]::IsNullOrWhiteSpace($inputVal) -and $current) {
        $inputVal = $current
    }
    Set-Variable -Name $key -Value $inputVal -Scope 1
    return $inputVal
}

function write_env([string]$key, [string]$value) {
    $lines = @()
    if (Test-Path $script:ENV_FILE) {
        $lines = Get-Content $script:ENV_FILE | Where-Object { $_ -notmatch "^\s*$([regex]::Escape($key))\s*=" }
    }
    $lines += "$key=$value"
    Set-Content -Path $script:ENV_FILE -Value $lines
    $script:WRITTEN_ENV.Add($key)
    Write-Host "  ✓ wrote " -ForegroundColor Green -NoNewline
    Write-Host "$key → $script:ENV_FILE"
}

function set_secret([string]$name, [string]$value) {
    if (Get-Command gh -ErrorAction SilentlyContinue) {
        try {
            $value | gh secret set $name 2>$null
            $script:WRITTEN_SECRET.Add($name)
            Write-Host "  ✓ set GitHub secret " -ForegroundColor Green -NoNewline
            Write-Host $name
            return
        } catch {}
    }
    $script:SKIPPED.Add("GitHub secret $name (set manually: gh secret set $name)")
    warn "Skipped GitHub secret $name: gh not authenticated or available"
}

function set_var([string]$name, [string]$value) {
    if (Get-Command gh -ErrorAction SilentlyContinue) {
        try {
            gh variable set $name --body $value 2>$null
            Write-Host "  ✓ set GitHub variable " -ForegroundColor Green -NoNewline
            Write-Host $name
            return
        } catch {}
    }
    $script:SKIPPED.Add("GitHub variable $name")
    warn "Skipped GitHub variable $name: gh not authenticated or available"
}

function finish() {
    Clear-ScreenSafe
    Write-Host "`n  ✓ Setup complete`n" -ForegroundColor Green
    if ($script:WRITTEN_ENV.Count -gt 0) {
        note ("wrote " + $script:WRITTEN_ENV.Count + " value(s) to $script:ENV_FILE: " + ($script:WRITTEN_ENV -join ', '))
    }
    if ($script:WRITTEN_SECRET.Count -gt 0) {
        note ("set " + $script:WRITTEN_SECRET.Count + " GitHub secret(s): " + ($script:WRITTEN_SECRET -join ', '))
    }
    if ($script:SKIPPED.Count -gt 0) {
        Write-Host "`n" -NoNewline
        warn "Still to do by hand:"
        foreach ($s in $script:SKIPPED) {
            note "  - $s"
        }
    }
    Write-Host "`n"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage per step the human takes.
# Replace the example below. Set $TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

$TOTAL_STAGES = 1

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe: API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask "STRIPE_PUBLISHABLE_KEY" "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret "STRIPE_SECRET_KEY" "Paste the secret key:"
write_env "STRIPE_PUBLISHABLE_KEY" $STRIPE_PUBLISHABLE_KEY
write_env "STRIPE_SECRET_KEY" $STRIPE_SECRET_KEY
set_secret "STRIPE_SECRET_KEY" $STRIPE_SECRET_KEY

finish
