#!/usr/bin/env node
/**
 * A wizard walks a human through a manual procedure, step by step.
 * Generated by the /wizard skill for Node.js (cross-platform macOS, Linux, Windows).
 *
 * Everything above the "STAGES" marker is the wizard library: do not hand-edit
 * it. Author the per-step stages below the marker.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync, spawnSync } from 'node:child_process';
import readline from 'node:readline';

const isWindows = process.platform === 'win32';
const isMac = process.platform === 'darwin';

const colors = {
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  reset: '\x1b[0m',
  blue: '\x1b[34m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m'
};

let TOTAL_STAGES = 0;
let _STAGE_INDEX = 0;
const ENV_FILE = process.env.ENV_FILE || '.env';
const WRITTEN_ENV = [];
const WRITTEN_SECRET = [];
const SKIPPED = [];

function clearScreen() {
  if (process.stdout.isTTY) {
    process.stdout.write('\x1b[2J\x1b[3J\x1b[H');
  }
}

async function pause(msg = 'Press Enter to continue') {
  process.stdout.write(`  ${colors.dim}${msg}${colors.reset} `);
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question('', () => {
      rl.close();
      resolve();
    });
  });
}

async function banner(title) {
  clearScreen();
  console.log(`\n  ${colors.bold}${colors.cyan}${title}${colors.reset}`);
  console.log(`  ${colors.dim}${TOTAL_STAGES} stages\n${colors.reset}`);
  console.log(`  ${colors.dim}You drive the browser; this wizard tells you exactly what to do and`);
  console.log('  captures the values you copy back. Stop any time with Ctrl+C and re-run');
  console.log(`  later, since it remembers values already saved.${colors.reset}\n`);
  await pause('Ready to start?');
}

function stage(name) {
  clearScreen();
  _STAGE_INDEX++;
  console.log(`\n${colors.bold}${colors.cyan}▸ Stage ${_STAGE_INDEX}/${TOTAL_STAGES} · ${name}${colors.reset}\n`);
}

function say(msg) {
  console.log(`  ${msg}`);
}

function step(msg) {
  console.log(`  ${colors.cyan}•${colors.reset} ${msg}`);
}

function note(msg) {
  console.log(`  ${colors.dim}${msg}${colors.reset}`);
}

function warn(msg) {
  console.log(`  ${colors.yellow}⚠ ${msg}${colors.reset}`);
}

function open_url(url) {
  console.log(`  ${colors.green}↗ opening${colors.reset} ${url}`);
  try {
    if (isMac) {
      spawnSync('open', [url], { stdio: 'ignore' });
    } else if (isWindows) {
      spawnSync('cmd.exe', ['/c', 'start', '""', url], { stdio: 'ignore' });
    } else {
      // Linux / WSL
      const openers = ['wslview', 'xdg-open', 'open'];
      let opened = false;
      for (const op of openers) {
        const check = spawnSync('which', [op], { stdio: 'ignore' });
        if (check.status === 0) {
          spawnSync(op, [url], { stdio: 'ignore' });
          opened = true;
          break;
        }
      }
      if (!opened) warn(`Could not open browser automatically; visit manually: ${url}`);
    }
  } catch {
    warn(`Could not open browser automatically; visit manually: ${url}`);
  }
}

async function confirm(question) {
  process.stdout.write(`  ${colors.yellow}? ${question} [y/N] ${colors.reset}`);
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question('', (ans) => {
      rl.close();
      resolve(/^y(es)?$/i.test(ans.trim()));
    });
  });
}

function getExistingEnv(key) {
  if (!fs.existsSync(ENV_FILE)) return null;
  const content = fs.readFileSync(ENV_FILE, 'utf8');
  for (const line of content.split('\n')) {
    const match = line.match(new RegExp(`^\\s*${key}\\s*=\\s*(.*)$`));
    if (match) {
      let val = match[1].trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      return val;
    }
  }
  return null;
}

async function ask(key, prompt) {
  const current = getExistingEnv(key);
  const promptText = current
    ? `  ${colors.bold}${prompt}${colors.reset} ${colors.dim}[Enter keeps current]${colors.reset} `
    : `  ${colors.bold}${prompt}${colors.reset} `;

  process.stdout.write(promptText);
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question('', (ans) => {
      rl.close();
      const val = ans.trim() === '' && current ? current : ans.trim();
      resolve(val);
    });
  });
}

async function ask_secret(key, prompt) {
  const current = getExistingEnv(key);
  const promptText = current
    ? `  ${colors.bold}${prompt}${colors.reset} ${colors.dim}[Enter keeps current]${colors.reset} `
    : `  ${colors.bold}${prompt}${colors.reset} `;

  process.stdout.write(promptText);

  return new Promise((resolve) => {
    let input = '';
    const wasRaw = process.stdin.isRaw;
    if (process.stdin.isTTY) process.stdin.setRawMode(true);
    process.stdin.resume();

    const onData = (chunk) => {
      const str = chunk.toString();
      for (const ch of str) {
        if (ch === '\n' || ch === '\r' || ch === '\u0004') {
          process.stdin.pause();
          process.stdin.removeListener('data', onData);
          if (process.stdin.isTTY) process.stdin.setRawMode(wasRaw);
          process.stdout.write('\n');
          const val = input.trim() === '' && current ? current : input.trim();
          resolve(val);
          return;
        } else if (ch === '\u0003') {
          // Ctrl+C
          process.exit(1);
        } else if (ch === '\u0008' || ch === '\x7f') {
          // Backspace
          input = input.slice(0, -1);
        } else {
          input += ch;
        }
      }
    };

    process.stdin.on('data', onData);
  });
}

function write_env(key, value) {
  let lines = [];
  if (fs.existsSync(ENV_FILE)) {
    lines = fs.readFileSync(ENV_FILE, 'utf8').split('\n').filter((l) => !new RegExp(`^\\s*${key}\\s*=`).test(l));
  }
  const formattedVal = /\s|#/.test(value) ? `"${value}"` : value;
  lines.push(`${key}=${formattedVal}`);
  fs.writeFileSync(ENV_FILE, lines.filter((l) => l.trim().length > 0).join('\n') + '\n', 'utf8');
  WRITTEN_ENV.push(key);
  console.log(`  ${colors.green}✓ wrote${colors.reset} ${key} → ${ENV_FILE}`);
}

function set_secret(name, value) {
  try {
    execSync(`gh secret set "${name}" --body "${value}"`, { stdio: 'ignore' });
    WRITTEN_SECRET.push(name);
    console.log(`  ${colors.green}✓ set${colors.reset} GitHub secret ${name}`);
  } catch {
    SKIPPED.push(`GitHub secret ${name} (set manually: gh secret set ${name})`);
    warn(`Skipped GitHub secret ${name}: gh not authenticated or available`);
  }
}

function set_var(name, value) {
  try {
    execSync(`gh variable set "${name}" --body "${value}"`, { stdio: 'ignore' });
    console.log(`  ${colors.green}✓ set${colors.reset} GitHub variable ${name}`);
  } catch {
    SKIPPED.push(`GitHub variable ${name}`);
    warn(`Skipped GitHub variable ${name}: gh not authenticated or available`);
  }
}

function finish() {
  clearScreen();
  console.log(`\n  ${colors.bold}${colors.green}✓ Setup complete${colors.reset}\n`);
  if (WRITTEN_ENV.length > 0) {
    note(`wrote ${WRITTEN_ENV.length} value(s) to ${ENV_FILE}: ${WRITTEN_ENV.join(', ')}`);
  }
  if (WRITTEN_SECRET.length > 0) {
    note(`set ${WRITTEN_SECRET.length} GitHub secret(s): ${WRITTEN_SECRET.join(', ')}`);
  }
  if (SKIPPED.length > 0) {
    console.log('');
    warn('Still to do by hand:');
    for (const s of SKIPPED) {
      note(`  - ${s}`);
    }
  }
  console.log('');
}

// ──────────────────────────────────────────────────────────────────────────
// STAGES: author this section. One stage per step the human takes.
// Replace the example below. Set TOTAL_STAGES to match the stages you write.
// ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES = 1;

async function run() {
  await banner('Stripe setup');

  // ── Example stage: replace with your real steps ─────────────────────────
  stage('Stripe: API keys');
  say("We'll grab your Stripe test keys and store them for local dev + CI.");
  open_url('https://dashboard.stripe.com/test/apikeys');
  step('On the API keys page, copy the Publishable key (starts pk_test_).');
  const STRIPE_PUBLISHABLE_KEY = await ask('STRIPE_PUBLISHABLE_KEY', 'Paste the publishable key:');
  step("Click 'Reveal test key' on the Secret key row, then copy it.");
  const STRIPE_SECRET_KEY = await ask_secret('STRIPE_SECRET_KEY', 'Paste the secret key:');
  write_env('STRIPE_PUBLISHABLE_KEY', STRIPE_PUBLISHABLE_KEY);
  write_env('STRIPE_SECRET_KEY', STRIPE_SECRET_KEY);
  set_secret('STRIPE_SECRET_KEY', STRIPE_SECRET_KEY);

  finish();
}

run().catch((err) => {
  console.error('\nWizard encountered an error:', err.message);
  process.exit(1);
});

