#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill for macOS and Linux.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "could not open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "could not open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Antigravity & Model Context Protocol (MCP) Setup Wizard"

# ── Stage 1: Skill Junction Linking ─────────────────────────────────────────
stage "Antigravity Skill Linking"
say "We will link all 38 skills into your local Antigravity directories (~/.agents/skills and ~/.gemini/config/skills)."
step "Running link-skills script to create symlinks..."
if node scripts/link-skills.mjs; then
  printf '  %s✓ Skills successfully linked!%s\n' "$GREEN" "$RESET"
else
  warn "Skill linking encountered an issue. Please check permissions."
fi
pause "Press Enter to proceed to API credentials."

# ── Stage 2: Gemini API Key ──────────────────────────────────────────────────
stage "Gemini API Credentials"
say "We will capture your Google AI Studio / Gemini API key for external tool integration and custom models."
open_url "https://aistudio.google.com/app/apikey"
step "Click 'Create API key' or select an existing project."
step "Copy the generated API key."
ask_secret GEMINI_API_KEY "Paste your Gemini API Key:"
if [[ -n "${GEMINI_API_KEY:-}" ]]; then
  write_env GEMINI_API_KEY "$GEMINI_API_KEY"
fi

# ── Stage 3: Brave Search API Key ────────────────────────────────────────────
stage "Brave Search API Credentials (MCP Search)"
say "Brave Search provides live web indexing and search tools for the Antigravity research subagent."
open_url "https://brave.com/search/api/"
step "Sign in or create a free Brave Search API account."
step "Navigate to API Keys and copy your Data for Search subscription key."
ask_secret BRAVE_API_KEY "Paste your Brave Search API Key (press Enter to skip):"
if [[ -n "${BRAVE_API_KEY:-}" ]]; then
  write_env BRAVE_API_KEY "$BRAVE_API_KEY"
fi

# ── Stage 4: GitHub Personal Access Token ────────────────────────────────────
stage "GitHub Personal Access Token"
say "A GitHub Personal Access Token allows Antigravity to query issues, PRs, and repositories via MCP."
open_url "https://github.com/settings/tokens/new?description=antigravity-mcp&scopes=repo,read:org"
step "Configure token expiration and confirm the 'repo' and 'read:org' scopes are selected."
step "Click 'Generate token' at the bottom of the page, then copy the token."
ask_secret GITHUB_PERSONAL_ACCESS_TOKEN "Paste your GitHub Token:"
if [[ -n "${GITHUB_PERSONAL_ACCESS_TOKEN:-}" ]]; then
  write_env GITHUB_PERSONAL_ACCESS_TOKEN "$GITHUB_PERSONAL_ACCESS_TOKEN"
fi

# ── Stage 5: Configure MCP Server Manifests ──────────────────────────────────
stage "MCP Server Manifest Generation"
say "We will generate .agents/mcp_config.json for workspace-level MCP integration."

node -e '
import fs from "node:fs";
const braveKey = process.env.BRAVE_API_KEY || "";
const ghToken = process.env.GITHUB_PERSONAL_ACCESS_TOKEN || "";
const mcpConfigPath = ".agents/mcp_config.json";

const config = { mcpServers: {} };
if (braveKey) {
  config.mcpServers["brave-search"] = {
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-brave-search"],
    env: { BRAVE_API_KEY: braveKey }
  };
}
if (ghToken) {
  config.mcpServers["github"] = {
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    env: { GITHUB_PERSONAL_ACCESS_TOKEN: ghToken }
  };
}

if (Object.keys(config.mcpServers).length > 0) {
  fs.writeFileSync(mcpConfigPath, JSON.stringify(config, null, 2) + "\n");
  console.log("  \x1b[32m✓\x1b[0m wrote MCP servers to " + mcpConfigPath);
} else {
  console.log("  No MCP server credentials configured; skipping mcp_config.json generation.");
}
'

finish

