title: agy-skills
description: Agent skills for Google Antigravity (AGY)
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

